#!/bin/bash

## This Script outputs an ascii bar as a dunst
## notification. This can be used for verbose
## volume / brightness control or for always
## on top output of progress of other sorts.
##
## Usage: $1 - Current value of progress (0 - 100)
##	  $2 - Arrow direction (any int +/-)
##	  $3 - Text icon to output
##	  $4 - Notification ID

# Setup strings
begLine="  _  "
endLine="  ▔  "
emptyLine=" | | "
incLine=" |▲| "
decLine=" |▼| "

# Set variables
maxTime=1630
curVal=$(( $1 - ($1 % 5) ))
if [ $2 -gt 0 ]; then
   dirLine=$incLine
else
   dirLine=$decLine
fi

function outputBar {
   # Print bar
   echo $begLine
   for i in {1..20}
      do
	 curIndex=$(( 100 - (($i-1) * 5 )  ))
         if [ $curIndex -eq $curVal ]; then
            echo $dirLine
         else
            echo $emptyLine
         fi
      done
   echo $endLine

   # Print percentage and icon
   echo $1%
   echo $2
}

# Output notification
varOut=$(outputBar $1 $3)
dunstify -r $4 -t "$maxTime" "$varOut"
