#!/bin/sh

## A script to list all available user scripts in all
## subdirectories of $HOME/exe/...

exeDir="$HOME/exe/"

begLn="┌─"
midLn="├─"
endLn="└─"
dirIn="--"

colDef=$(tput setaf 7)
colDir=$(tput setaf 6)
colLns=$(tput setaf 3)
colSep=$(tput setaf 1)

#######################################################

function printDir {
   ## $1 Directory to print
   ## $2 Characters to be printed before lines
   ## $3 Omit Operators? (o=yes, *=no)
   ## $4 Recursive? (r=yes, *=no)

   [[   $3 = "o" ]] && curFiles=$(find $1 -maxdepth 1 -type f | grep -v "_" | awk -F ${1} '{ print $2 }')
   [[ ! $3 = "o" ]] && curFiles=$(find $1 -maxdepth 1 -type l | grep "_" | awk -F ${1} '{ print $2 }')
   curDirs=$(find $1 -maxdepth 1 -type d)
   spcChrs=$2

   echo -e "$colDir$spcChrs[$(basename $1)]$colDef" 

   while read -r line; do
      lnvar=$midLn
      [[ $(echo "$curFiles" | head -n1) = $line ]] && lnvar=$begLn
      [[ $(echo "$curFiles" | tail -n1) = $line ]] && lnvar=$endLn
      echo "$colLns$spcChrs$lnvar$colDef $(echo $line | tr -d "/")"
   done <<< "$curFiles"
   
   if [ "$4" = "r" ] ; then
      while read -r line; do
         [[ ! $line = $1 ]] && printDir $line "$spcChrs$dirIn" o r
         spcChrs=${spcChrs:1}
      done <<< "$curDirs"
   fi
}


function printSeperator {
   ## $1 Tesxt to be displayed
   ## $2 String to surround $1

   echo -e "\e[1m$2$colSep$1$colDef$2\e[0m"
}

figlet Scripts
printSeperator "Operator Scripts" "###"
printDir $exeDir "" "" ""
echo ""
printSeperator "User Scripts" "###"
printDir $exeDir "" o r
