#!/bin/sh

## Executes a script from any subfolder of the exe folder.
## Useful in situations where the $PAATH variable is not set.

## $1 - Script name

avScripts="$(find /home/lh/exe -type f)\n$(find /home/lh/exe -type l)"

while read -r l; do
	[[ "$1" = $(basename $l) ]] && hasFound="yes" && eval $l ${*:2}
done <<< $(echo -e "$avScripts")

if [ "$hasFound" = "" ]; then
  echo "(!) - No matching script $1 found." && exit 1
else
  exit 0
fi
